"""Tests for match adjudication and Elo estimation.

Elo is what gates network promotion during training, so a bug here does not just
misreport progress -- it lets a worse network replace a better one, and every
subsequent iteration trains on data generated by the regression.
"""

from __future__ import annotations

import numpy as np
import pytest

from quoridor import fastrules as fr
from quoridor.arena import (
    DRAW,
    MatchResult,
    decide_by_progress,
    elo_to_score,
    fit_elo,
    score_to_elo,
)


def position(p0: int, p1: int) -> np.ndarray:
    st = fr.initial_state()
    st[fr.IDX_P0] = p0
    st[fr.IDX_P1] = p1
    return st


# ----------------------------------------------------------- elo conversion


def test_even_score_is_zero_elo():
    assert score_to_elo(0.5) == pytest.approx(0.0, abs=1e-6)


def test_elo_score_roundtrip():
    for elo in (-400, -150, 0, 150, 400):
        assert score_to_elo(elo_to_score(elo)) == pytest.approx(elo, abs=1e-3)


def test_known_elo_values():
    # A 300-point favourite scores ~85%.
    assert elo_to_score(300) == pytest.approx(0.849, abs=0.01)
    assert score_to_elo(0.75) == pytest.approx(190.8, abs=1.0)


# --------------------------------------------------------- shutout handling


def test_shutout_gives_finite_elo():
    """A 40-0 result is complete separation; the prior must keep it finite."""
    r = MatchResult("a", "b", wins_a=40, wins_b=0, draws=0, mean_plies=50)
    assert r.score_a == 1.0
    assert 400 < r.elo_diff < 1000, f"implausible Elo {r.elo_diff}"
    assert np.isfinite(r.elo_ci95) and r.elo_ci95 < 1000


def test_more_games_narrows_the_interval():
    small = MatchResult("a", "b", 20, 0, 0, 50)
    large = MatchResult("a", "b", 400, 0, 0, 50)
    assert large.elo_diff > small.elo_diff, "more evidence should imply a larger gap"
    assert large.elo_ci95 < small.elo_ci95, "more evidence should narrow the interval"


def test_even_match_reports_zero():
    r = MatchResult("a", "b", 50, 50, 0, 60)
    assert r.score_a == 0.5
    assert r.elo_diff == pytest.approx(0.0, abs=1e-6)


def test_draws_count_as_half():
    r = MatchResult("a", "b", wins_a=10, wins_b=10, draws=20, mean_plies=60)
    assert r.score_a == 0.5
    assert r.games == 40


# ------------------------------------------------------------- elo fitting


def test_fit_recovers_synthetic_ratings():
    """Given scores generated from known ratings, the fit should recover them."""
    true = {"weak": 0.0, "mid": 200.0, "strong": 400.0}
    names = list(true)
    pairwise = []
    for i, a in enumerate(names):
        for b in names[i + 1:]:
            pairwise.append((a, b, elo_to_score(true[a] - true[b]), 400))

    fitted = fit_elo(pairwise, names)
    for name in names:
        assert fitted[name] == pytest.approx(true[name], abs=40), (
            f"{name}: fitted {fitted[name]:.0f} vs true {true[name]:.0f}"
        )


def test_fit_is_anchored_at_first_name():
    pairwise = [("a", "b", 0.9, 100)]
    fitted = fit_elo(pairwise, ["a", "b"])
    assert fitted["a"] == pytest.approx(0.0, abs=1e-6)
    assert fitted["b"] < 0


def test_fit_stays_finite_under_total_separation():
    """A ladder of shutouts must not send ratings to infinity."""
    names = ["a", "b", "c"]
    pairwise = [("a", "b", 1.0, 50), ("a", "c", 1.0, 50), ("b", "c", 1.0, 50)]
    fitted = fit_elo(pairwise, names)
    assert all(np.isfinite(v) for v in fitted.values())
    assert all(abs(v) < 5000 for v in fitted.values()), f"ratings blew up: {fitted}"
    assert fitted["b"] < fitted["a"] and fitted["c"] < fitted["b"]


# ------------------------------------------------------------ adjudication


def test_progress_adjudication_picks_the_closer_player():
    scratch = fr.make_scratch()
    # Player 0 is one row from home (row 8); player 1 is still at the far end.
    st = position(7 * 9 + 4, 8 * 9 + 0)
    assert decide_by_progress(st, scratch) == 0

    # Mirror the situation: player 1 is one row from home (row 0).
    st = position(0 * 9 + 4, 1 * 9 + 0)
    assert decide_by_progress(st, scratch) == 1


def test_progress_adjudication_draws_on_equal_distance():
    scratch = fr.make_scratch()
    st = position(4 * 9 + 4, 4 * 9 + 0)  # both four steps from goal
    assert fr.shortest_path_len(st, 0, scratch) == fr.shortest_path_len(st, 1, scratch)
    assert decide_by_progress(st, scratch) == DRAW


def test_progress_adjudication_respects_walls():
    """A wall that lengthens a player's route should flip the adjudication."""
    scratch = fr.make_scratch()
    st = position(4 * 9 + 4, 4 * 9 + 0)
    assert decide_by_progress(st, scratch) == DRAW
    # Wall off player 0's straight route, forcing a detour.
    st[fr.WH_OFF + 4 * fr.W + 3] = 1
    st[fr.WH_OFF + 4 * fr.W + 5] = 1
    if fr.shortest_path_len(st, 0, scratch) > fr.shortest_path_len(st, 1, scratch):
        assert decide_by_progress(st, scratch) == 1
